force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/ItemRef_Id__c.field-meta.xml
<CustomField>
    <fullName>ItemRef_Id__c</fullName>
    <label>ItemRef Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/handlers/InvoiceLineItemTriggerHandler.cls
public class InvoiceLineItemTriggerHandler {
    
    /**
     * Before Update Trigger Handler
     * @param ilis Invoice Line Items from Trigger.new
     */
    public static void beforeUpdateHandler(List<Invoice_Line_Item__c> ilis){
        linkProducts(ilis);
    }

    /**
     * Before Insert Trigger Handler
     * @param ilis Invoice Line Items from Trigger.new
     */
    public static void beforeInsertHandler(List<Invoice_Line_Item__c> ilis){
        linkProducts(ilis);
    }

    /**
     * Link invoice line items to products based on product id in QBO
     * @param ilis Invoice Line Items from Trigger.new
     */
    private static void linkProducts(List<Invoice_Line_Item__c> ilis){
        Set<String> productQBIds = new Set<String>();
        for(Invoice_Line_Item__c ili : ilis){
            if(String.isNotBlank(ili.ItemRef_Id__c)){
                productQBIds.add(ili.ItemRef_Id__c);
            }
        }

        List<Product2> products = [SELECT Id, QB_Id__c 
                                    FROM Product2 
                                    WHERE QB_Id__c in: new List<String>(productQBIds)];
        Map<String, Id> productMap = new Map<String, Id>();
        for(Product2 p : products){
            productMap.put(p.QB_Id__c, p.Id);
        }
        for(Invoice_Line_Item__c ili : ilis){
            if(String.isNotBlank(ili.ItemRef_Id__c) && productMap.containsKey(ili.ItemRef_Id__c)){
                ili.Product__c = productMap.get(ili.ItemRef_Id__c);
            }
        }  
    }
}