force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Allow_Online_ACH_Payment__c.field-meta.xml
<CustomField>
    <fullName>Allow_Online_ACH_Payment__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Allow Online ACH Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Allow_Online_CC_Payment__c.field-meta.xml
<CustomField>
    <fullName>Allow_Online_CC_Payment__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Allow Online CC Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Bill_City__c.field-meta.xml
<CustomField>
    <fullName>Bill_City__c</fullName>
    <label>Bill City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Bill_Country__c.field-meta.xml
<CustomField>
    <fullName>Bill_Country__c</fullName>
    <label>Bill Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Bill_State__c.field-meta.xml
<CustomField>
    <fullName>Bill_State__c</fullName>
    <label>Bill State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Bill_Street__c.field-meta.xml
<CustomField>
    <fullName>Bill_Street__c</fullName>
    <label>Bill Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Bill_Suite__c.field-meta.xml
<CustomField>
    <fullName>Bill_Suite__c</fullName>
    <label>Bill Suite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Bill_Zip__c.field-meta.xml
<CustomField>
    <fullName>Bill_Zip__c</fullName>
    <label>Bill Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/QB_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/QB_Synctoken__c.field-meta.xml
<CustomField>
    <fullName>QB_Synctoken__c</fullName>
    <label>QB Synctoken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Ship_City__c.field-meta.xml
<CustomField>
    <fullName>Ship_City__c</fullName>
    <label>Ship City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Ship_Country__c.field-meta.xml
<CustomField>
    <fullName>Ship_Country__c</fullName>
    <label>Ship Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Ship_State__c.field-meta.xml
<CustomField>
    <fullName>Ship_State__c</fullName>
    <label>Ship State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Ship_Street__c.field-meta.xml
<CustomField>
    <fullName>Ship_Street__c</fullName>
    <label>Ship Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Ship_Suite__c.field-meta.xml
<CustomField>
    <fullName>Ship_Suite__c</fullName>
    <label>Ship Suite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Ship_Zip__c.field-meta.xml
<CustomField>
    <fullName>Ship_Zip__c</fullName>
    <label>Ship Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Shipping_Handling__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Handling__c</fullName>
    <label>Shipping &amp; Handling</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <label>Terms</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Due On Receipt</fullName>
            </value>
            <value>
                <fullName>Net 15</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/ItemRef_Id__c.field-meta.xml
<CustomField>
    <fullName>ItemRef_Id__c</fullName>
    <label>ItemRef Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/LineNum__c.field-meta.xml
<CustomField>
    <fullName>LineNum__c</fullName>
    <label>LineNum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Date__c</fullName>
    <label>Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Taxable__c.field-meta.xml
<CustomField>
    <fullName>Taxable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Taxable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/invoice/QBInvoicePushBatch.cls
global class QBInvoicePushBatch implements Database.Batchable<sobject>,Database.AllowsCallouts, Schedulable{
    global void execute(SchedulableContext SC){
        QBInvoicePushBatch batch= new QBInvoicePushBatch();
        Database.executeBatch(batch, 50);
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator('SELECT Id, ' +
        'Due_Date__c,' +
        'Subtotal__c,' +
        'Balance__c,' +
        '  Name, ' + 
        '  QB_Id__c,' +
        '  Opportunity__r.Account.QB_Id__c,' +
        '  QB_SyncToken__c,' +
        '  Terms__c,' +
        '  Tax__c,' +
        '  Email__c,' +
        '  Shipping_Handling__c,' +
        '  Allow_Online_ACH_Payment__c,' +
        '  Allow_Online_CC_Payment__c,' +
        '  Bill_City__c,' +
        '  Bill_Street__c,' +
        '  Bill_Suite__c,' +
        '  Bill_State__c,' +
        '  Bill_Zip__c,' +
        '  Bill_Country__c,' +
        '  Ship_City__c,' +
        '  Ship_Street__c,' +
        '  Ship_Suite__c,' +
        '  Ship_Zip__c,' +
        '  Ship_State__c,' +
        '  Ship_Country__c,' +
        '  (SELECT Id, Unit_Price__c, Quantity__c, ' +
        '           Amount__c, ItemRef_Id__c, QB_Id__c,' +
        '           Product__r.QB_Id__c, Product__r.QB_Description__c,' +
                   'LineNum__c,' +
                   'Product__c, Description__c, Taxable__c,' +
                   'Service_Date__c' + 
          'FROM Invoice_Line_Items__r) WHERE QB_ID__c = null'
          );
    }
    
    global void Execute(Database.BatchableContext BC,List<Invoice__c> invList){
        QBInvoiceHelper.createOrUpdateInvoices(invList);
    } 
    
    global void finish(Database.BatchableContext BC){
        System.debug('Finished');
    }
    
}