force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/QB_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/ItemRef_Id__c.field-meta.xml
<CustomField>
    <fullName>ItemRef_Id__c</fullName>
    <label>ItemRef Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test/InvoiceLineItemTest.cls
@isTest public class InvoiceLineItemTest {

    @TestSetup
    static void makeData(){
        Account a = new Account();
        a.Name = 'Test Name From Apex';
        a.QB_Id__c = 'test';
        insert a;

        Product2 p = new Product2();
        p.Name = 'TEST FROM Apex';
        p.QB_Id__c = 'TESTXD';
        insert p;

        Invoice__c inv = new Invoice__c();
        inv.name = 'INV-XXXX';
        inv.Customer_Id__c = 'test';
        insert inv;

    }

    @isTest static void testInsert(){
        Invoice__c inv = [SELECT Id FROM Invoice__c WHERE Name = 'INV-XXXX'];
        Invoice_Line_Item__c ili = new Invoice_Line_Item__c();
        ili.ItemRef_Id__c = 'TESTXD';
        ili.Invoice__c = inv.Id;
        Test.startTest();
        insert ili;
        Test.stopTest();
        Product2 p = [SELECT Id FROM Product2 WHERE Name = 'TEST FROM Apex'];
        Invoice_Line_Item__c returnILI = [SELECT Id, Product__c FROM Invoice_Line_Item__c where Id =: ili.Id];
        System.assert(returnILI.Product__c == p.Id);
    }

    @isTest static void testUpdate(){
        Invoice__c inv = [SELECT Id FROM Invoice__c WHERE Name = 'INV-XXXX'];
        Invoice_Line_Item__c ili = new Invoice_Line_Item__c();
        ili.Invoice__c = inv.Id;
        insert ili;
        Test.startTest();
        ili.ItemRef_Id__c = 'TESTXD';
        update ili;
        Test.stopTest();
        Product2 p = [SELECT Id FROM Product2 WHERE Name = 'TEST FROM Apex'];
        Invoice_Line_Item__c returnILI = [SELECT Id, Product__c FROM Invoice_Line_Item__c where Id =: ili.Id];
        System.assert(returnILI.Product__c == p.Id);
    }
}