force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/QB_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Taxable__c.field-meta.xml
<CustomField>
    <fullName>Taxable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Taxable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/invoice/QBInvoiceTest.cls
@isTest private class QBInvoiceTest {

    @TestSetup
    static void makeData(){
        Account a = new Account();
        a.Name = 'Jizuke';
        a.QB_Id__c = 'Test';
        insert a;

        Contact c = new Contact();
        c.LastName = 'Jizuke Kazoo';
        c.AccountId = a.Id;
        insert c;
        
        Invoice__c inv = new Invoice__c();
        inv.Name = 'INV-XXXX';
        inv.QB_Id__c = 'test-inv';
        insert inv;

        Invoice_Line_Item__c ili = new Invoice_Line_Item__c();
        ili.Invoice__c = inv.Id;
        ili.Quantity__c = 1.0;
        ili.Unit_Price__c = 2.0;
        ili.Taxable__c = true;
        insert ili; 
    }

    @isTest static void testController(){
        Test.setMock(HttpCalloutMock.class, new QBMock());

        Invoice__c inv = QBInvoiceHelper.getInvoice([SELECT Id FROM Invoice__c WHERE Name = 'INV-XXXX'].Id);

        Test.startTest();

        PageReference pageRef = Page.QBInvoiceVF; // Add your VF page Name here
        pageRef.getParameters().put('Id', String.valueOf(inv.Id));
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController stdInvoice = new ApexPages.StandardController(inv);
        QBInvoice_Controller controller = new QBInvoice_Controller(stdInvoice);
        controller.syncQB();
        Test.stopTest();

        System.assert(controller != null);

    }

    @isTest static void testCreateController(){
        Test.setMock(HttpCalloutMock.class, new QBMock());

        Invoice__c inv = QBInvoiceHelper.getInvoice([SELECT Id FROM Invoice__c WHERE Name = 'INV-XXXX'].Id);

        Test.startTest();

        PageReference pageRef = Page.QBInvoiceVF; // Add your VF page Name here
        pageRef.getParameters().put('Id', String.valueOf(inv.Id));
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController stdInvoice = new ApexPages.StandardController(inv);
        QBInvoiceCreate_Controller controller = new QBInvoiceCreate_Controller(stdInvoice);
        controller.syncQB();
        Test.stopTest();

        System.assert(controller != null);

    }

    @isTest static void testInvoiceCreate(){
        Test.setMock(HttpCalloutMock.class, new QBMock());
        Invoice__c inv = QBInvoiceHelper.getInvoice([SELECT Id FROM Invoice__c WHERE Name = 'INV-XXXX'].Id);
        List<Invoice_Line_Item__c> ilis = getILIs(inv.Id);
        Test.startTest();
        QBInvoiceResponseJSON invoice = QBCallout.createInvoice(QBMap.mapInvoice(inv, ilis, 'testId'));
        Test.stopTest();

        System.assert(invoice != null);
    }

    @isTest static void testInvoiceQuery(){
        Test.setMock(HttpCalloutMock.class, new QBMock());
        Invoice__c inv = QBInvoiceHelper.getInvoice([SELECT Id FROM Invoice__c WHERE Name = 'INV-XXXX'].Id);
        Test.startTest();
        QBInvoiceQueryJSON invoice = QBCallout.getInvoice(inv);
        Test.stopTest();

        System.assert(invoice != null);
        System.assert(invoice.QueryResponse != null);
    }

    @isTest static void testInvoiceBatch(){
        Test.setMock(HttpCalloutMock.class, new QBMock());

        Test.startTest();
        QBInvoiceBatch batch= new QBInvoiceBatch();
        Database.executeBatch(batch);
        Test.stopTest();

        System.assert(batch != null);
    }

    @isTest static void testInvoiceQueueable(){
        Test.setMock(HttpCalloutMock.class, new QBMock());
        Test.startTest();
        System.enqueueJob(new QBInvoiceQueueable(0,0,0,0));
        Test.stopTest();
        
    }

    // Implement a mock http response generator for QBAuth. 
    public class QBMock implements HttpCalloutMock 
    { 
        public HTTPResponse respond(HTTPRequest req) 
        {  
            HTTPResponse res = new HTTPResponse();
 
            if (req.getEndpoint().contains('query')) {
                res.setBody(QBInvoiceQueryJSON_Test.json);
                res.setStatusCode(200);
            } else if (req.getEndpoint().contains('invoice')) {
                res.setBody(QBInvoiceResponseJSON_Test.json);
                res.setStatusCode(200);
            } else {
                System.assert(false, 'unexpected endpoint ' + req.getEndpoint());
                return null;
            }

            return res;
        } 
    
    }

    private static List<Invoice_Line_Item__c> getILIs(Id invId){
        return [SELECT Id, Invoice__c, Unit_Price__c,
                     Quantity__c, Product__c, Amount__c,
                     Product__r.QB_Id__c, Product__r.QB_Description__c,
                     QB_Id__c, Description__c,
                     Taxable__c
                FROM Invoice_Line_Item__c 
                WHERE Invoice__c =: invId];
    }
}