force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment (QIME)</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/QB_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/payment/QBPaymentController.cls
public with sharing class QBPaymentController {

    public Id pmtId {get;set;}
    public Payment__c pmt {get;set;}

    public QBPaymentController(ApexPages.StandardController controller) {
        pmtId = controller.getRecord().Id;
        pmt = QBPaymentHelper.getPayment(pmtId);
    }

    public Pagereference syncQB(){
        if(String.isBlank(pmt.QB_Id__c)){
            throw new QBException('Please enter a QB Id');
        }

        QBPaymentQueryJSON queryJson = QBCallout.getPayment(pmt);
        List<Payment__c> payments = QBMap.mapPayments(queryJson);
        Database.update(payments, false);

        return new PageReference('/'+ pmtId);
    }
    
}