force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment (QIME)</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/QB_Id__c.field-meta.xml
<CustomField>
    <fullName>QB_Id__c</fullName>
    <externalId>true</externalId>
    <label>QB Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/payment/QBPaymentBatch.cls
global class QBPaymentBatch implements Database.Batchable<sobject>, Database.AllowsCallouts, Schedulable {
  global void execute(SchedulableContext SC) {
    QBPaymentBatch batch = new QBPaymentBatch();
    Database.executeBatch(batch, 50);
  }
  global Database.QueryLocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator('SELECT Id FROM Account LIMIT 1');
  }

  global void Execute(Database.BatchableContext BC, List<Account> accList) {
    String query =
      'select * from Payment WHERE Metadata.LastUpdatedTime > \'' +
      String.valueOf(
        Datetime.now()
          .addhours(-2)
          .formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')
      ) +
      '\'';
    QBPaymentQueryJSON queryJson = QBCallout.queryPayments(query);
    List<Payment__c> payments = QBMap.mapPayments(queryJson);
    Database.UpsertResult[] upsertResults = Database.upsert(
      payments,
      Payment__c.qb_Id__c,
      false
    );
  }
  global void finish(Database.BatchableContext BC) {
    System.debug('Finished');
  }
}